### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by rrahl0** [pop-os/cosmic-reader#2]
Please add a license file, so I can package it for openSUSE.

**Comment by jackpot51** [comment]
I've added the license (GPLv3), but a warning that this (along with cosmic-player) is in a very early state and not meant to be part of the first stable COSMIC release. When it is ready, it will be linked from the cosmic-epoch project.

**Comment by rrahl0** [comment]
I fully understand. I just want them to be already packaged and in the respective development project (which needs a valid OSS license)
